baseURL = "https://apiobuild.com"
title = "apio: microservices platform to create custom business softwares easily."
languageCode = "en-us"
themesDir = "themes"
theme = "custom-theme"
relativeURLs = true
googleAnalytics = "UA-71133003-2"
disqusShortname = "apiobuild-com"

[params]
  footer = "Made by Lulu in her free time."
  image = "/images/logo_square.png"

[taxonomies]
  tag = "tags"

[params.meta]
  meta_description = "apio's portfolio microservices enable businesses to build secure, scalable, and cost-effective custom softwares to support your business needs, so you can focus on delivering business values to your customers. Our platform allows users to integrate various APIs with simple configuration with or without code. Our pay-as-you-use pricing model allows you to try out ideas without worrying about the costs. We believe quality softwares should be accessible to everyone, we pride ourselves in connecting developers and businesses to build impactful software solutions of any size."
  meta_og_type = "website"
  og_image = "images/favicon.png"
  meta_twitter_card = "summary"
  meta_twitter_site = "@l1990790120"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[[menu.main]]
	name = "product"
	url = "#product"
    weight = 1

[[menu.main]]
	name = "why us"
	url = "#why-us"
    weight = 2

[[menu.main]]
    name = "sign up"
    url = "#sign-up"
    weight = 3

[[menu.main]]
    name = "team"
    url = "#team"
    weight = 4

[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"


[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    noClasses = true
    style = "rainbow_dash"
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true  
    autoHeadingIDType = "blackfriday"
