baseURL = "apiobuild.com"
title = "apio"
languageCode = "en-us"
themesDir = "themes"
theme = "custom-theme"
relativeURLs = true
googleAnalytics = "UA-71133003-2"
disqusShortname = "l1990790120"

[params]
  footer = "Made by Lulu in her free time."

[taxonomies]
  tag = "tags"

[params.meta]
  meta_description = "apio is a platform connecting developers and businesses to build impactful software solutions of any size"
  meta_og_type = "services"
  og_image = "images/favicon.png"
  meta_twitter_card = "summary"
  meta_twitter_site = "@l1990790120"

[[menu.main]]
	name = "why us"
	url = "#why-us"
    weight = 1

[[menu.main]]
    name = "sign up"
    url = "#sign-up"
    weight = 2

[[menu.main]]
    name = "team"
    url = "#team"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"


[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    style = "rainbow_dash"
