baseURL = "www.apiobuild.com"
title = "apio"
languageCode = "en-us"
themesDir = "themes"
theme = "custom-theme"
relativeURLs = true
googleAnalytics = "UA-71133003-2"


[params]
  footer = "Made by Lulu in her free time."

[params.meta]
  meta_description = "apio is a platform connecting developers to impactful projects and business to partners to build solutions of any size"
  meta_og_type = "services"
  og_image = "images/logo.png"
  meta_twitter_card = "summary"
  meta_twitter_site = "@l1990790120"

[[menu.main]]
	name = "WHY US"
	url = "#why-us"
    weight = 1

[[menu.main]]
    name = "CONTACT"
    url = "#contact"
    weight = 2

[[menu.main]]
    name = "TEAM"
    url = "#team"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

[markup.goldmark.renderer]
  unsafe= true
