name: Publish Content
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --global user.email "${GITHUB_EMAIL}"
        git config --global user.name "${GITHUB_USER}"
        git fetch --unshallow
        rm -rf public
        echo "checkout to master as worktree"
        git worktree prune && git worktree add -B master public origin/master

        echo "run npm install"        
        cd themes/custom-theme
        npm install
        cd ../..

        echo "generate static content in public"
        docker run --rm -v $(pwd):/src -v $(pwd)/public:/src/public \
          peaceiris/hugo:v2.6.0 -b 'https://apiobuild.com/' --gc --minify
        echo "push public to master"
        cd public
        git add --all
        git commit -m "Publishing to master"
        git push
      env:
        GITHUB_EMAIL: ${{ secrets.GITHUBEMAIL }}
        GITHUB_USER: ${{ secrets.GITHUBUSER }}  
